name: Taskmaster
author: Halflove
version: 1.0
main: me.Halflove.Quests.Main.Main
softdepend: [WorldGuard, HolographicDisplays, WGRegionEvents, Vault, Towny]
api-version: 1.18
commands:
  tasks:
    aliases: [task]
    usage: </Command>
    description: Internal.